# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NIBMConnect' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NIBMConnect
	pod 'Firebase/Core'
	pod 'Firebase/Database'
	pod 'Firebase/Auth'
	pod 'GoogleSignIn'
	pod 'Firebase/Storage'

  target 'NIBMConnectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NIBMConnectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
